env:
  CIRRUS_CLONE_DEPTH: 1

task:
  matrix:
    - name: 13-CURRENT
      freebsd_instance:
        image_family: freebsd-13-0-snap
    - name: 12.1-STABLE
      freebsd_instance:
        image_family: freebsd-12-1-snap
    - name: 12.1-RELEASE
      freebsd_instance:
        image_family: freebsd-12-1
  env:
    matrix:
      - ARCH: i386
      - ARCH: amd64
        AS_ROOT: yes
      - ARCH: amd64
        AS_ROOT: no
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg upgrade -y
    - pkg install -y autoconf automake libtool kyua sudo
  script:
    - env JUNIT_OUTPUT=$(pwd)/test-results.xml ./admin/travis-build.sh
  always:
    junit_artifacts:
      path: "test-results.xml"
      type: text/xml
      format: junit
